### ISSUE TITLE
prettier is changing all code files in windows

### ISSUE THREAD

**Issue by cl-shaharshavit-rnd** [MapColonies/ts-server-boilerplate#29]
**Describe the bug**
after cloning repository in windows machine and running prettier all code files are changed.

**To Reproduce**
1. clone the repository in windows
2. run "npm install"
3. run "npm run lint:fix"
4. run "git status" and see all most files as "modified"

**Expected behavior**
no changes to show as the committed code passed linting

**Additional context**
this is caused by the linter forcing LF line endings in all files and git changing the line endings to match the host OS when cloning and pulling.

this can be fixed by either:
- removing line ending configuration from prettier
- setting the line endings on all files to LF in the git attributes

**Comment by syncush** [comment]
https://github.com/MapColonies/ts-server-boilerplate/blob/bed1221a1993649608e384362e179ae45d5425ab/.gitattributes#L1-L2

**Comment by cl-shaharshavit-rnd** [comment]
vscode (like most modern windows app) works fine with either.
tough i don't see a reason for prettier to enforce it in the first place as git manages line endings on its on.

**Comment by syncush** [comment]
Please run the command and post here the output
```sh
git config core.autocrlf
```

**Comment by syncush** [comment]
Please look at 
https://stackoverflow.com/a/20653073
