### ISSUE TITLE
Bug: NODE_TLS_REJECT_UNAUTHORIZED=0 shouldn't exist in PROD

### ISSUE THREAD

**Issue by asafMasa** [MapColonies/ts-server-boilerplate#43]
Error when expected certificate doesn't exist

 NODE_TLS_REJECT_UNAUTHORIZED = 0 - is not a valid option as described here 
https://stackoverflow.com/questions/35633829/node-js-error-process-env-node-tls-reject-unauthorized-what-does-this-mean

"Node is complaining because the TLS (SSL) certificate it's been given is self-signed (i.e. it has no parent - a depth of 0). It expects to find a certificate signed by another certificate that is installed in your OS as a trusted root.

Your "fix" is to disable Node from rejecting self-signed certificates by allowing ANY unauthorized certificate.

Your fix is insecure and shouldn't really be done at all, but is often done in development (it should never be done in production).

The proper solution should be to put the self-signed certificate in your trusted root store OR to get a proper certificate signed by an existing Certificate Authority (which is already trusted by your server).

As an additional point your logging should thus read "Disabling Node's rejection of invalid/unauthorized certificates""

**Comment by syncush** [comment]
1. Either install the certificates on the image
2. use NODE_TLS_REJECT_UNAUTHORIZED=0

Each problem requires its unique solution, I would not use the same method in all cases.
